# ==============================================================================
# AI INSTRUCTION: CRITICAL STRING ESCAPING SOP
# ==============================================================================
# When calling the GitHub MCP tools listed below, you MUST prevent JSON parsing 
# errors and newline stripping by following these exact steps:
# 
# 1. Save your long-form text (e.g., Markdown, PR body, file content) to a local file.
# 2. Run this script: `python escape_string.py <file_path>`
# 3. Capture the EXACT raw output string generated by this script.
# 4. Inject that exact output directly into the corresponding tool parameter.
#    -> DO NOT modify, format, or re-escape the string yourself.
#    -> DO NOT remove any newline (\n) characters.
#    -> Just pass the raw result directly as the parameter value.
#
# Target Tools & Parameters:
# ------------------------------------------------------------------------------
# create_or_update_file                 -> content
# push_files                            -> files[].content
# create_pull_request                   -> body
# update_pull_request                   -> body
# pull_request_review_write             -> body
# add_reply_to_pull_request_comment     -> body
# issue_write                           -> body
# add_issue_comment                     -> body
# projects_write                        -> body
# create_gist                           -> content
# update_gist                           -> content
# ==============================================================================

import json
import sys

def main():
    if len(sys.argv) < 2:
        print("Usage: python escape_string.py <file_path>")
        sys.exit(1)
        
    with open(sys.argv[1], 'r', encoding='utf-8') as f:
        content = f.read()
        
    print(json.dumps(content, ensure_ascii=False))

if __name__ == "__main__":
    main()